name: flutter_form_builder
description: Package to build Material Form with fields like TextField, DropDown, Switches etc. with ability to create custom FormFields and composability and reuse validation functions.
version: 4.0.0-alpha.3
homepage: https://github.com/danvick/flutter_form_builder

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  country_code_picker: ^1.4.0
  country_pickers: ^1.3.0
  date_range_picker: ^1.0.6
  datetime_picker_formfield: ^1.0.0
  flutter_colorpicker: ^0.3.4
  flutter_chips_input: ^1.8.3
  flutter_touch_spin: ^1.0.1
  flutter_typeahead: ^1.8.5
  group_radio_button: ^1.0.1
  image_picker: ^0.6.7+2
  intl: ^0.16.1
  phone_number: ^0.6.2+3
  rating_bar: ^0.2.0
  signature: ^3.1.2
  validators: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.1
  pedantic: ^1.9.0
  intl_translation:

flutter:
